site_name: Racoon
site_description: Racoon is a fast, fully customizable web framework for Rust focusing on simplicity.
repo_url: https://github.com/tejmagar/racoon

nav:
  - 'Introduction': index.md
    
  - 'Basics':
    - Getting Started: getting-started.md
    - Routing: routing.md
    - Response: response.md
    - Shared Context: shared-context.md
    - Cookies: cookies.md
    - Session: session.md
    - WebSocket: websocket-basics.md
  
  - 'Form Handling': 
    - Reading form data: reading-form-data.md
    - Form validation: form-validation.md

  - 'Middlewares': middleware.md
  - 'Advanced':
    - Server binding options: server-binding-options.md
    - Server configurations: server-configurations.md
    - Stopping server: stopping-server.md

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

